config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: :index
  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find params[:id]
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    @task = Task.find params[:id]
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit a task </h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', value: @task.title %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control', value: @task.details %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<h1> List of tasks </h1>
<% @tasks.each do |task| %>

  <% if task.completed == true %>
    <h3><input type="checkbox" checked><%= link_to task.title, task_path(task.id) %></h3>
  <% else %>
    <h3><input type="checkbox" unchecked><%= link_to task.title, task_path(task.id) %></h3>
  <% end %>
<% end %>

<p> <%= link_to "Add a new task", new_path %> </p>

app/views/tasks/new.html.erb
<h1> Add a new task </h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1> Details of the task </h1>
<%= @task.title %>
<%= @task.details %>
<p> completed : <%=  @task.completed %> </p>
<%= link_to "Back to the list",tasks_path %>
<%= link_to "Edit a task",edit_path %>

<%= link_to "Delete a task", task_path,
      method: :delete,
      data: { confirm: "Are you sure?" } %>